#!/usr/bin/env bash
set -euo pipefail && cd "$(dirname "${BASH_SOURCE[0]}")/.."

set -x

export AWS_DEFAULT_REGION=us-east-1

stack_name="fxime-fun"

aws cloudformation deploy \
    --no-fail-on-empty-changeset \
    --capabilities CAPABILITY_IAM \
    --template-file template-fun.yaml \
    --stack-name "${stack_name}"

aws cloudformation describe-stacks \
        --stack-name "${stack_name}" \
        --query "Stacks[0].Outputs"
