#!/usr/bin/env bash

set -euo pipefail

arg="${1-}"

if [[ "$arg" == "--json" ]]; then
    kind=json
elif [[ "$arg" == "--edn" ]]; then
    kind=edn
else
    echo First argument must be --json or --edn
    exit 1
fi

shift

url=http://localhost:8080

if [[ "${1-}" == "--prod" ]]; then
    url=https://fxime.com
    shift
fi

s=$(cat "$@" | urlencode)

open "$url/app/from-hash/${kind}#data=${s}"
