#!/usr/bin/env bash
set -euo pipefail && cd "$(dirname "${BASH_SOURCE[0]}")/.."

our_temp_dir=$(mktemp -d 2>/dev/null || mktemp -d -t 'our_temp_dir')
function cleanup_temp_dir() { rm -rf "$our_temp_dir" ; } && trap "cleanup_temp_dir" EXIT

DIST_ID="$(python3 -c 'import uuid; print(uuid.uuid4())')"
export DIST_ID

rm -rf dist
mkdir -p dist
npx shadow-cljs release release
( cd public ; git ls-files ) > "$our_temp_dir/list.txt"
rsync -a --files-from "$our_temp_dir/list.txt" public/ dist/
mv dist/9a57cb91-581d-4d51-a539-b656be2a0b69 dist/"$DIST_ID"
find dist -type f -print0 | \
    xargs -0 perl -p -i \
          -e 's/9a57cb91-581d-4d51-a539-b656be2a0b69/$ENV{DIST_ID}/ge'

VERSION=$(git rev-list --count main)
VERSION=$(printf "0.%04d" "$VERSION")
export VERSION

perl -p -i \
     -e 's/"0.0000"/"$ENV{VERSION}"/ge' \
     dist/index.html
