#!/usr/bin/env bash
set -euo pipefail && cd "$(dirname "${BASH_SOURCE[0]}")/.."

DIST_ID="$(python3 -c 'import uuid; print(uuid.uuid4())')"

rm -rf dist
mkdir -p dist
npx shadow-cljs release release
rsync -a public/{css,index.html} dist/
find dist -type f -print0 | \
    xargs -0 perl -p -i \
          -e 's/9a57cb91-581d-4d51-a539-b656be2a0b69/$ENV{DIST_ID}/ge'
